### ISSUE TITLE
Publishing to Apache

### ISSUE THREAD

**Issue by kagoryu** [huludini/aura-kingdom-web#1]
After invoking the command php artisan key:generate, I have created an Alias in my http.conf to point to the public folder directory. Is this the correct next step or am I missing something?

**Comment by tomirons** [comment]
That would be correct, so it wouldn't have `public` in every URL. It would work like this one. http://ak.vividgaming.org/

**Comment by kagoryu** [comment]
What would be the minimum parameters for the <Directory> structure?

**Comment by tomirons** [comment]
I always setup my websites on Ubuntu, over the years I found it easier than any other OS, I can also setup virtual hosts fairly easy too.

This is the virtual host I have for my website https://ranktheserver.com, I removed a couple lines cause I have SSL setup on the website.

```
<VirtualHost *:80>
    ServerAdmin admin@ranktheserver.com
    ServerName ranktheserver.com
    ServerAlias www.ranktheserver.com
    DocumentRoot /var/www/ranktheserver.com/public
    <Directory />
        Options FollowSymLinks
        AllowOverride All
    </Directory>
    <Directory /var/www/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride All
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Order allow,deny
        Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    Alias /doc/ "/usr/share/doc/"
    <Directory "/usr/share/doc/">
        Options Indexes MultiViews FollowSymLinks
        AllowOverride None
        Order deny,allow
        Deny from all
        Allow from 127.0.0.0/255.0.0.0 ::1/128
    </Directory>

</VirtualHost>
```

**Comment by kagoryu** [comment]
Looks like I am missing some permissions, I have set 777 to the following:

storage/app/
storage/framework/
storage/logs/
bootstrap/cache/
.env

But I am getting Error 500 (Something went wrong). It goes away if I set 777 to the whole Aura-Kingdom-Web folder.

**Comment by tomirons** [comment]
You need to set the permissions recursively to the `storage` and `bootstrap` folders. If that doesn't work past the last error from the `storage/logs/laravel.log` file and I'll help you out.

**Comment by tomirons** [comment]
I'm assuming since you posted another issue, you fixed this one?
