### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by vo6tu7** [huludini/aura-kingdom-web#12]
Why i can't login to admin ? :(
Im use VPS
![image](https://user-images.githubusercontent.com/56047520/74594383-4dc81300-5068-11ea-9982-87347f42887e.png)

**Comment by tomirons** [comment]
@vo6tu7 this means that you don't have the host configured correctly. It has nothing to do with the panel. [This should help you.](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04) 😃

**Comment by vo6tu7** [comment]
Still error :(
![1](https://user-images.githubusercontent.com/56047520/74667576-12e3ed80-51d6-11ea-8e89-141faa228541.png)

**Comment by tomirons** [comment]
[Try this](https://lmgtfy.com/?q=php+pdo+could+not+find+driver)

**Comment by vo6tu7** [comment]
Everything was ok
But it still does not work :(
![Untitled](https://user-images.githubusercontent.com/56047520/74676348-6eb77200-51e8-11ea-822f-b2240637e5ac.png)

**Comment by tomirons** [comment]
Are you still getting the same error as the first one?

**Comment by vo6tu7** [comment]
DEMO
http://159.89.195.151/web

**Comment by vo6tu7** [comment]
I fixed the PDO error
But when I uploaded to my VPS
Could not run

**Comment by tomirons** [comment]
Try changing the root of the virtual host from `/var/www/public_html/web` to `/var/www/public_html/web/public`.

**Comment by vo6tu7** [comment]
I do not understand very much
I use CentOS 6.9
How do I change the directory? :(

**Comment by tomirons** [comment]
It's in the configuration for the virtual host. Usually located in `/etc/apache/` from the root directory on your server.
