### ISSUE TITLE
Vote App - Not Crediting Reward

### ISSUE THREAD

**Issue by kagoryu** [huludini/aura-kingdom-web#2]
I have enabled Vote in the Applications and created an RTS account (yey!). I have added the details, specifically reward 500 AP but doesn't seem to get into the user account.

Anything that I missed?

**Comment by tomirons** [comment]
I just tested this and it seems to be adding the reward just fine. If your talking about the value in-game, you may need to re-log to see the new value.

**Comment by kagoryu** [comment]
I am seeing my AP value unchanged on the web. You may want to test my install at http://gak.servegame.com

**Comment by tomirons** [comment]
I just tried it and got 1k AP.

In your `.env` file, make sure the database names are correct.

```
# Game Database Names
DB_ACCOUNT=ffaccount
DB_GAME=ffdb1
DB_MEMBER=ffmember
```

**Comment by kagoryu** [comment]
I can see you got 1k AP on there. Let me confirm if it's in the game database. Database names are case-sensitive right? I modified mine to:

```
# Game Database Names
DB_ACCOUNT=FFAccount
DB_GAME=FFDB1
DB_MEMBER=FFMember

```

**Comment by tomirons** [comment]
If I received 1k AP, then it's working fine, cause it updates one of the game databases.

**Comment by kagoryu** [comment]
I can see it, weird my test account did not increment on first try. I will test further.

**Comment by tomirons** [comment]
If this comes back, please create another issue.
