### ISSUE TITLE
Vote App - AP Reward Does Not Increment

### ISSUE THREAD

**Issue by kagoryu** [huludini/aura-kingdom-web#4]
Whenever someone votes, AP count resets to the reward amount. Example, Player A has 10,000 AP clicks Vote for 1,000 AP. Player gets 1,000 AP instead of 11,000 AP.

**Comment by tomirons** [comment]
You can use this hot fix for now til I release another update:

Open `app/Http/Controllers/Front/VoteController.php` and replace line `68` with this

```
$user->pvalues = ( $site->double_rewards ) ? ( $site->reward_amount * 2 ) + $user->pvalues : $site->reward_amount + $user->pvalues;
```

**Comment by kagoryu** [comment]
I have tested the hot fix and I can confirm that it works. AP is now added correctly.
Thanks.
