### ISSUE TITLE
Automate Ranking

### ISSUE THREAD

**Issue by hambapraduka** [huludini/aura-kingdom-web#8]
Adding this cron job will automate ranking system updates.
- \* \* \* \* php /var/www/html/artisan schedule:run >> /dev/null 2>&1
# 

Please detailed instruction

![image](https://cloud.githubusercontent.com/assets/22659621/19151892/74f8f6d8-8bf9-11e6-8f97-f72f4925512f.png)

**Comment by tomirons** [comment]
You need to setup a cronjob on your server, that's what it means.
